### ISSUE TITLE
can't install it

### ISSUE THREAD

**Issue by yurara** [noggaholic/machinima-studio#14]
https://imgur.com/a/FtyRqYA

I installed nodejs, and tried installer.bat. but it makes these errors.

```
 C:\GW2Machina>echo "Installing Machinima Studio dependencies"
"Installing Machinima Studio dependencies"

C:\GW2Machina>cd app/

C:\GW2Machina\app>call npm install
npm WARN launcher@1.0.0 No description
npm WARN launcher@1.0.0 No repository field.

audited 4 packages in 1.224s
found 0 vulnerabilities


> bswap@1.2.0 install C:\GW2Machina\gw2\node_modules\bswap
> node-gyp rebuild


C:\GW2Machina\gw2\node_modules\bswap>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\GW2Machina\gw2\node_modules\bswap
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN eslint-config-airbnb@6.2.0 requires a peer of eslint@^2.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@6.2.0 requires a peer of eslint-plugin-react@^4.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@9.0.0 requires a peer of eslint-plugin-import@^2.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN gw2@1.0.0 No description
npm WARN gw2@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bswap@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bswap@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Targal\AppData\Roaming\npm-cache\_logs\2018-06-02T19_52_22_137Z-debug.log
"Done! Now close this windows and open Machinima Studio"
```

**Comment by karliky** [comment]
Solved with the latest release https://github.com/noggaholic/machinima-studio/releases/tag/2.0
